/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TvShowIdRouteImport } from './routes/tv-show.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as TvShowIdSeasonRouteImport } from './routes/tv-show.$id_.$season'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowIdRoute = TvShowIdRouteImport.update({
  id: '/tv-show/$id',
  path: '/tv-show/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TvShowIdSeasonRoute = TvShowIdSeasonRouteImport.update({
  id: '/tv-show/$id_/$season',
  path: '/tv-show/$id/$season',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/tv-show/$id': typeof TvShowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv-show/$id/$season': typeof TvShowIdSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/tv-show/$id': typeof TvShowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv-show/$id/$season': typeof TvShowIdSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/tv-show/$id': typeof TvShowIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/tv-show/$id_/$season': typeof TvShowIdSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/search' | '/tv-show/$id' | '/api/auth/$' | '/tv-show/$id/$season'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/tv-show/$id' | '/api/auth/$' | '/tv-show/$id/$season'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/tv-show/$id'
    | '/api/auth/$'
    | '/tv-show/$id_/$season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  TvShowIdRoute: typeof TvShowIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TvShowIdSeasonRoute: typeof TvShowIdSeasonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-show/$id': {
      id: '/tv-show/$id'
      path: '/tv-show/$id'
      fullPath: '/tv-show/$id'
      preLoaderRoute: typeof TvShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv-show/$id_/$season': {
      id: '/tv-show/$id_/$season'
      path: '/tv-show/$id/$season'
      fullPath: '/tv-show/$id/$season'
      preLoaderRoute: typeof TvShowIdSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  TvShowIdRoute: TvShowIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TvShowIdSeasonRoute: TvShowIdSeasonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
